ci: docker build and push

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -24,4 +24,27 @@ jobs:
         run: npm install
       
       - name: "Ejecutar pruebas"
-        run: npm test || true
+        run: npm test || true # exit code por credenciales externas
+  
+  docker-submit:
+    needs: build-and-test
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/main' # Solo ejecutar en main
+
+    steps:
+      - name: "Descargar código"
+        uses: actions/checkout@v3
+
+      - name: "Login en DockerHub"
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      
+      - name: "Construir y publicar imagen"
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:latest
+        
